PRAGMA foreign_keys = OFF;
DROP TABLE IF EXISTS wallet_transactions;
DROP TABLE IF EXISTS wallets;
DROP TABLE IF EXISTS driver_locations;
DROP TABLE IF EXISTS push_tokens;
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS order_events;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS menu_items;
DROP TABLE IF EXISTS coupons;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS addresses;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS support_tickets;
DROP TABLE IF EXISTS support_messages;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS rate_limits;
DROP TABLE IF EXISTS drivers;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS users;
PRAGMA foreign_keys = ON;
