const API="https://fairfood.fairfood100.workers.dev";
function euro(c){return (Number(c||0)/100).toFixed(2).replace(".",",")+" €"}
async function api(path, options={}){
  const token = localStorage.ff_token || localStorage.ff_rest_token || localStorage.ff_driver_token || localStorage.ff_admin_token || "";
  const res = await fetch(API+path, {
    ...options,
    headers: {"content-type":"application/json", authorization: token ? "Bearer "+token : "", ...(options.headers||{})},
    body: options.body && typeof options.body !== "string" ? JSON.stringify(options.body) : options.body
  });
  const data = await res.json().catch(()=>({}));
  if(!res.ok || data.success===false) throw new Error(data.error?.message || "API error");
  return data;
}

let token=localStorage.ff_token||"", me=null, currentRestaurant=null, cart=[];
async function login(email="customer@fairfood.local", password="Password123!"){const d=await api("/api/auth/login",{method:"POST",body:{email,password}});localStorage.ff_token=d.token;token=d.token;me=d.user;return d}
async function ensure(){if(token)return;await login()}
async function registerBox(){const name=prompt("Name"); if(!name)return; const email=prompt("Email"); const password=prompt("Password","Password123!"); const d=await api("/api/auth/register",{method:"POST",body:{role:"customer",name,email,password}});localStorage.ff_token=d.token;alert("Registered");showHome()}
async function showHome(){hideAll();document.getElementById("restaurantList").style.display="block";await ensure();const d=await api("/api/restaurants");document.getElementById("restaurantList").innerHTML=d.restaurants.map(r=>`<article class="restaurant-card" onclick="openRestaurant('${r.id}')"><img src="${r.cover_image||''}"><div class="body"><h1>${r.name}</h1><div class="meta">⭐ ${r.rating} · ${r.cuisine}<br>🕒 ${r.delivery_time_min}-${r.delivery_time_max} Min. · 🚴 ${euro(r.delivery_fee_cents)} · 🧺 Min. ${euro(r.min_order_cents)}</div></div></article>`).join("")}
async function openRestaurant(id){currentRestaurant=(await api("/api/restaurants")).restaurants.find(r=>r.id===id);const menu=(await api(`/api/restaurants/${id}/menu`)).items;const cats=[...new Set(menu.map(i=>i.category))];hideAll();const page=document.getElementById("restaurantPage");page.style.display="block";page.innerHTML=`<div class="hero-img" style="background-image:url('${currentRestaurant.cover_image}')"></div><h1>${currentRestaurant.name}</h1><div class="meta">⭐ ${currentRestaurant.rating} · ${currentRestaurant.cuisine}</div><div class="promo">Coupon: WELCOME10 أو SAVE2</div>${cats.map(c=>`<h2 class="section-title">${c}</h2>${menu.filter(i=>i.category===c).map(i=>`<div class="item"><div><h3>${i.name}</h3><b class="price">${euro(i.price_cents)}</b><p class="desc">${i.description||""}</p>${i.tags?`<span class="tag">${i.tags}</span>`:""}</div><img src="${i.image||''}"><button class="plus" onclick='addCart(${JSON.stringify(i).replaceAll("'","")})'>+</button></div>`).join("")}`).join("")}`;renderCart()}
function addCart(item){const x=cart.find(c=>c.id===item.id);if(x)x.qty++;else cart.push({...item,qty:1});renderCart()}
function renderCart(){const bar=document.getElementById("cartBar");if(!cart.length){bar.style.display="none";return}const sum=cart.reduce((s,i)=>s+i.price_cents*i.qty,0)+(currentRestaurant?.delivery_fee_cents||0);bar.style.display="flex";bar.innerHTML=`<strong>${cart.reduce((s,i)=>s+i.qty,0)} Artikel · ${euro(sum)}</strong><button class="btn" onclick="checkout()">Bestellen</button>`}
async function checkout(){const addr=prompt("Lieferadresse:","Graf-Folke-Bernadotte-Straße 1, Frankfurt");if(!addr)return;const coupon=prompt("Coupon optional:","");const d=await api("/api/orders",{method:"POST",body:{restaurantId:currentRestaurant.id,deliveryAddress:addr,couponCode:coupon||null,items:cart.map(i=>({menuItemId:i.id,quantity:i.qty})),paymentMethod:"cash"}});cart=[];renderCart();showOrder(d.orderId)}
async function showOrders(){hideAll();const pg=document.getElementById("ordersPage");pg.style.display="block";await ensure();const d=await api("/api/orders/my");pg.innerHTML="<h1>Meine Bestellungen</h1>"+d.orders.map(o=>`<div class="order" onclick="showOrder('${o.id}')"><b>${o.restaurant_name}</b><br><span class="status">${statusText(o.status,o.prep_time_min,o.eta_min)}</span><br>${euro(o.total_cents)}</div>`).join("")}
async function showOrder(id){hideAll();const d=await api(`/api/orders/${id}`);const pg=document.getElementById("ordersPage");pg.style.display="block";pg.innerHTML=`<h1>Bestellung</h1><div class="panel"><h2>${d.order.restaurant_name}</h2><p class="status">${statusText(d.order.status,d.order.prep_time_min,d.order.eta_min)}</p><p>${d.items.map(i=>i.quantity+"× "+i.name).join("<br>")}</p><h2>${euro(d.order.total_cents)}</h2>${d.order.status==="completed"?`<button class="btn" onclick="rate('${d.order.id}','restaurant','${d.order.restaurant_id}')">Bewerten</button>`:""}</div><h2>Verlauf</h2>${d.events.map(e=>`<div class="order">${new Date(e.created_at).toLocaleString()}<br>${e.note}</div>`).join("")}`;setTimeout(()=>showOrder(id).catch(()=>{}),12000)}
async function showWallet(){hideAll();const pg=document.getElementById("walletPage");pg.style.display="block";const d=await api("/api/wallet");const n=await api("/api/notifications");pg.innerHTML=`<h1>Wallet</h1><div class="panel"><h2>${euro(d.wallet.balance_cents)}</h2><p>Pending: ${euro(d.wallet.pending_cents)}</p></div><h2>Notifications</h2>${n.notifications.map(x=>`<div class="order"><b>${x.title}</b><br>${x.body}</div>`).join("")}<button class="btn secondary" onclick="support()">Support</button>`}
async function support(){const msg=prompt("Message");if(msg)await api("/api/support/tickets",{method:"POST",body:{subject:"Customer support",message:msg}})}
async function rate(orderId,targetType,targetId){const stars=Number(prompt("Stars 1-5","5"));await api("/api/ratings",{method:"POST",body:{orderId,targetType,targetId,stars,comment:""}});alert("Thanks")}
function statusText(s,prep,eta){return {new:"Warten auf Restaurant",accepted_by_restaurant:`Restaurant accepted · ${prep||25} min`,preparing:"Wird zubereitet",ready_for_driver:"Wartet auf Fahrer",accepted_by_driver:"Fahrer zugeteilt",picked_up:"Fahrer hat Essen abgeholt",on_the_way:`Fahrer ist unterwegs · ${eta||10} min`,completed:"Geliefert",rejected_by_restaurant:"Abgelehnt",cancelled:"Storniert"}[s]||s}
function loginBox(){alert("Demo: customer@fairfood.local / Password123!")}
function hideAll(){["restaurantList","restaurantPage","ordersPage","walletPage"].forEach(id=>document.getElementById(id).style.display="none");document.getElementById("cartBar").style.display=cart.length?"flex":"none"}
showHome();
